### ISSUE TITLE
How to implement RLS?

### ISSUE THREAD

**Issue by marceloventura** [Microsoft/PowerBI-Developer-Samples#10]
Hey, How do I implement RLS using this example? [Here ](https://docs.microsoft.com/en-us/azure/power-bi-embedded/power-bi-embedded-rls) I can find an example of Embedded report with RLS using PowerBI Embedded Azure Service but it you [be discontinued](https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-migrate-from-powerbi-embedded/) and I can't find new examples about embedded + RLS.

Thank you!

**Comment by aberenguer** [comment]
Hello guys, I am looking for the same. Anyone found a sample to work with Embedded API and RLS? Many customers asking for it. Thanks,

**Comment by ali-hamud** [comment]
Hi, we will update this sample to use RLS as well.

**Comment by anders76** [comment]
Any news for this ?

**Comment by yeacer** [comment]
Any news for this ?Thanks

**Comment by ali-hamud** [comment]
Just search this file for RLS, you will find a sample code to work with RLS.
https://github.com/Microsoft/PowerBI-Developer-Samples/blob/master/App%20Owns%20Data/PowerBIEmbedded_AppOwnsData/Controllers/HomeController.cs

to see an example, bring a report where RLS is defined, change web.config to contain your own settings, and just run the solution.
in the URL you should pass user and roles. example:
EmbedReport?user=tammy&roles=manager,developer

solution is here:
https://github.com/Microsoft/PowerBI-Developer-Samples/tree/master/App%20Owns%20Data
