### ISSUE TITLE
groupId in PowerBIEmbedded_AppOwnsData solution

### ISSUE THREAD

**Issue by reza-h78** [Microsoft/PowerBI-Developer-Samples#12]
Hi,

I have all app settings populated for App Owns Data solution but don't know what is the groupId value should be and the project need that to run? 
Would you please guide me or share a link that where I can get groupId? Please note that I have created workspace and don't have any group.

Thanks

**Comment by nickraphael** [comment]
You can get it on the powerbi site from the URL.  Just browse to the workspace.

**Comment by ali-hamud** [comment]
groupId is the workspaceId.
you can get it either from URL or by calling groups API
https://msdn.microsoft.com/en-us/library/mt243842.aspx
