### ISSUE TITLE
App Owns Data Doesn't Run / Client Secret

### ISSUE THREAD

**Issue by johnbroderick** [Microsoft/PowerBI-Developer-Samples#13]
Upon running "App Owns Data Solution" with all parameters filled in correctly / get the following error:

ACS90014: The request body must contain the following parameter: 'client_secret or client_assertion'

**Comment by Karan-Chandwani** [comment]
What was the solution for this issue?

**Comment by ali-hamud** [comment]
just register native AAD application in place of web AAD application.

**Comment by Karan-Chandwani** [comment]
It worked. Thanks :+1:
