### ISSUE TITLE
Where is the sample that shows how to upload pbix files?

### ISSUE THREAD

**Issue by nickraphael** [Microsoft/PowerBI-Developer-Samples#14]
There used to be a sample console app called ProvisionSample that had all the code to create Workspaces and upload pbix files etc (you may recall it had options 1-10).  Of course this was for the old PowerBI Embedded that is being deprecated.  How do I do the same thing using the new model?  I converted the old sample code into powershell scripts to upload my reports and update the connection strings.  I need to produce a new set of powershell scripts to do the same in the new PowerBI world.

**Comment by ali-hamud** [comment]
There is no samples to upload a pbix file.
please try to use the library. use client.imports.PostImportWithFileInGroup method.
tell me if you have problems.

method definitions is in this file:
https://github.com/Microsoft/PowerBI-CSharp/blob/master/sdk/PowerBI.Api/Imports/V2/ImportsExtensions.cs

**Comment by ali-hamud** [comment]
Please re-open if the problem is not solved for you.
