### ISSUE TITLE
Operation returned an invalid status code 'Forbidden': App Only Sample Code

### ISSUE THREAD

**Issue by nithsk87** [Microsoft/PowerBI-Developer-Samples#15]
I am getting below error for App Only Sample Code when i click on Embed Report.

Please help me to resolve this

Operation returned an invalid status code 'Forbidden'

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Forbidden'

Source Error: 
Line 74:                 // Generate Embed Token. Line 75:                 var generateTokenRequestParameters = new GenerateTokenRequest(accessLevel: "view"); Line 76:                 var tokenResponse = await client.Reports.GenerateTokenInGroupAsync(GroupId, report.Id, generateTokenRequestParameters); Line 77:  Line 78:                 if (tokenResponse == null)
--

**Comment by ali-hamud** [comment]
Hi,
This could occur for many different reasons. mostly it's because the AAD token is expired or you are trying to access a group you are not a member of.
can you please give a request Id. you can find it in fiddler (or any other network capture tool).

**Comment by nithsk87** [comment]
Hi,
  In debug mode i am able to see group, report URL and report Id detail, but its failing in while retrieving token response(Below code). my power BI app Setting and Fiddler detail is copied in below attached Doc.
Appreciate help on this.
[PowerBI_Fiddler.docx](https://github.com/Microsoft/PowerBI-Developer-Samples/files/1232118/PowerBI_Fiddler.docx)

                 var tokenResponse = await client.Reports.GenerateTokenInGroupAsync(GroupId, report.Id, generateTokenRequestParameters);

**Comment by nithsk87** [comment]
Hi,
 Issue is resolved :) Just closed and reopened my Visual Studio there you go it started working :)
