### ISSUE TITLE
integrate-dashboard-web-app Input string was not in a correct format. 

### ISSUE THREAD

**Issue by tjmcdevitt** [Microsoft/PowerBI-Developer-Samples#16]
I download the integrate-dashboard-web-app and enter the ClientSecret and the ClientID values in the cloud.config file. But when I run the project I am getting this error "Input string was not in a correct format. " on this line

```
Line 35:             AuthenticationResult AR = AC.AcquireTokenByAuthorizationCode(code, new Uri(redirectUri), cc);
--
```

Is there some additaional setting I need to add to the Azure Active Directory? I dont see anything that related to the application for power BI in Azure

**Comment by ali-hamud** [comment]
what is the redirectUri you use?

**Comment by ali-hamud** [comment]
closing as no response.
