### ISSUE TITLE
you must use multi-factor authentication 

### ISSUE THREAD

**Issue by GielG** [Microsoft/PowerBI-Developer-Samples#18]
Hello,
I'm trying to get this sample work with some of my own data. But when I try to receive the Tile, Report or Dashboard I get an error With the description AADSTS50076 and: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access.

Do you know how I can achieve access? I have registered the app as Native in Azure. And Followed multiple tutorials for the right settings. 

Thanx in advance! 
Giel

**Comment by ali-hamud** [comment]
You are using an AAD which requires Multi-Factor authentication to sign in (enabled by an admin).
To use "App Owns Data" sample, please use an AAD which has no such requirement.

You can check this by going to "Conditional Access" in Azure Active Directory.
