### ISSUE TITLE
Error - invalid grant

### ISSUE THREAD

**Issue by RonPooters** [Microsoft/PowerBI-Developer-Samples#19]
Hi all,

{"error":"invalid_grant","error_description":"AADSTS65001: The user or administrator has not consented to use the application with ID 'REMOVED' named 'Microsoft.Azure.AnalysisServices'.

Any ideas what went wrong?

I did the following:
1. Create Azure AD app through https://dev.powerbi.com/apps
2. Create an app workspace in my PowerBI.com, added a report to it and published the app workspace
3. Downloaded the GitHub example (App Owns Data), and entered Client ID (from the AAD app), Group ID (from the Power BI app) and username/password

**Comment by ali-hamud** [comment]
Two things to check:
1) did you registered the app as Native app?
2) did you clicked the "Grant Permissions" in azure?

**Comment by RonPooters** [comment]
It was the 'Grant Permissions' that was missing. Thanks!

**Comment by RonPooters** [comment]
Now I'm stumbling onto the next error... 

'Operation returned an invalid status code 'Unauthorized' 
on this line: `var reports = await client.Reports.GetReportsInGroupAsync(GroupId);`

Not sure what is wrong. The workspace is created by the same AAD user that created the AAD app and is the same user authorizing in the Web.Config file.

**Comment by ali-hamud** [comment]
This could happen for different reasons:
1) Report.Read.All permission is not granted to the app.
2) the user that you signed in with in the sample doesn't have access to the group.

can you look in Network Traffic and tell what error do you have there?

**Comment by xabikos** [comment]
I am trying to test the sample on my subscription. It seems like a native app is the only way to access the Power BI REST API with the credentials of the user. 

What I don't understand is why then the UI in https://dev.powerbi.com/apps allow you to register a web app. In what scenario this could be used?

**Comment by ali-hamud** [comment]
please see "User Owns Data" scenario.
https://github.com/Microsoft/PowerBI-Developer-Samples/tree/master/User%20Owns%20Data

in this scenario, your app users need to sign in with their Power BI accounts, and you will show their reports and dashboards with their data.
