### ISSUE TITLE
'Not Found' during GetReportsInGroupAsync

### ISSUE THREAD

**Issue by new2powerbi** [Microsoft/PowerBI-Developer-Samples#20]
I have downloaded the power bi sample. I have worked through the authentication issues, I have assigned permissions through the azure portal, I have created a report on my power bi desktop, and published it to the workspace. However, when the program calls 
var reports = await client.Reports.GetReportsInGroupAsync(GroupId);
I get Server Error in '/' Application. Operation returned an invalid status code 'NotFound'
I have tried to search everywhere for this error but can't seem to figure out what I have missed to get this error. Any help would be appreciated? 
Not sure if I am posting in the correct spot for help either, please let me know the correct spot to post and delete if need be.

**Comment by ali-hamud** [comment]
please make sure the user you use to login (i.e. in web.config in the sample) does have permissions to the group in PowerBI.com

**Comment by new2powerbi** [comment]
Thank you for the reply. Yes using my login in the PowerBIEmbedded_AppOwnsData sample. I have made it through authentication but receiving the error on GetReportsInGroupAsync call.

**Comment by ali-hamud** [comment]
please put a breakpoint on the line you mentioned and see if you get there.
if yes, please see what is the value of GroupId, and see if it's valid.

**Comment by ali-hamud** [comment]
Please re-open if the problem is not solved for you.
