### ISSUE TITLE
GroupId must be a Guid object. Please select a group you own and fill its Id in web.config 

### ISSUE THREAD

**Issue by uthens** [Microsoft/PowerBI-Developer-Samples#21]
What is mean "GroupID" ?  and how to get it ? 

`<add key="groupId" value="" />`

**Comment by uthens** [comment]
I tied on this, but it's work.
https://community.powerbi.com/t5/Developer/New-Power-BI-Interfacing-embedding/m-p/203521#M6490

**Comment by somriar** [comment]
Your groupId is your workspace Id, you can find it in the URL when you go to PowerBI.com and going into one of your workspaces.
for example:
![image](https://user-images.githubusercontent.com/18301676/31053109-6a69fe86-a69e-11e7-8cff-d10b94692804.png)

**Comment by ali-hamud** [comment]
you can also find it calling groups rest api, or GetGroups method.

REST API:
see here: https://msdn.microsoft.com/en-us/library/mt243842.aspx
