### ISSUE TITLE
Error with parsing token "app owns data"

### ISSUE THREAD

**Issue by jvondermans** [Microsoft/PowerBI-Developer-Samples#23]
Hi,

First of all, let me say I'm not a coder, so this could be a silly question. I'm trying to embed a PowerBi report in a website with JavaSript. I've completed the steps, register the app, so I have the ClientID, Picked up the GroupID from the Azure ADGroup en filled that in in Web.config. I Also provided the necessary credentials. 

After I run tha application, I can choose dashboard, app or tile to embed en when I click report I'm getting an error:

 "error":"invalid_client","error_description":"AADSTS70002: The request body must contain the following parameter: 'client_secret or client_assertion'."

`
Regel 43:             // Authenticate using created credentials 
Regel 44:             var authenticationContext = new AuthenticationContext(AuthorityUrl); 
Regel 45:             var authenticationResult = await authenticationContext.AcquireTokenAsync(ResourceUrl, ClientId, credential); 
Regel 46:  
Regel 47:             if (authenticationResult == null)`
--

I can't find anywhere to leave My Client_secret, so I'm a bit lost. The documentation on The PowerBi.com Is not very clear in this matter, so any help would be welcome.

Jordy

**Comment by ali-hamud** [comment]
It seems that you are running "User Owns Data" sample.
This sample need a web application to be registered in AAD.
once you register a web app, you get client Id and client secret.
please follow the steps here and try:
https://github.com/Microsoft/PowerBI-Developer-Samples#user-owns-data-samples

let me know if it solves your issue.

**Comment by jvondermans** [comment]
Hi Ali,

Thanks for the quick response! I'm running the AppOwnsData solutionfile for Visual Studio. Filled in all required info en then Run the app.

in the error the path is there as well:
 PowerBI-Developer-Samples-master\App Owns Data\PowerBIEmbedded_AppOwnsData\Controllers\HomeController.cs    Regel: 45 

Any more ideas?

**Comment by ali-hamud** [comment]
So it must be the opposite. you registered web app, and you need to register native app. AppOwnsData  needs native app.

**Comment by jvondermans** [comment]
you were right! was the wrong app registration.

Get a different Error now though: 
"error":"invalid_grant","error_description":"AADSTS65001: The user or administrator has not consented to use the application with ID '

**Comment by ali-hamud** [comment]
click "Grant Permissions" in portal.azure.com while selecting the app you registered.

**Comment by jvondermans** [comment]
it works! thanks for your patience
