### ISSUE TITLE
Can't filter from a space contained string (ex : malitha rukshan) in Power BI REST API v2

### ISSUE THREAD

**Issue by MalithRukshan** [Microsoft/PowerBI-Developer-Samples#24]
**This code sample is not working**
var generateTokenRequestParameters =new GenerateTokenRequest("Edit", null, identities: new List<EffectiveIdentity> { new EffectiveIdentity(username: "Malitha Rukshan ", roles: new List<string> { "Manager" }, datasets: new List<string> { report.DatasetId }) });
                var tokenResponse = await client.Reports.GenerateTokenInGroupAsync(GroupId, report.Id, generateTokenRequestParameters);

 **But This code sample is working**
var generateTokenRequestParameters =new GenerateTokenRequest("Edit", null, identities: new List<EffectiveIdentity> { new EffectiveIdentity(username: "MalithaRukshan ", roles: new List<string> { "Manager" }, datasets: new List<string> { report.DatasetId }) });
                var tokenResponse = await client.Reports.GenerateTokenInGroupAsync(GroupId, report.Id, generateTokenRequestParameters);

In the Power BI data modal columns are appeared like this, 
![capture](https://user-images.githubusercontent.com/20617431/31534217-a3e85076-b013-11e7-965d-396e808bf88f.PNG)

It can be solved by removing the space between the names. But this is not a proper solution

**Comment by eligr** [comment]
Hi Malith!
This is indeed a documentation issue, the username property cannot accept spaces and several other special characters.
We'll fix the documentation ASAP.

Eli.
