### ISSUE TITLE
EmbedReport in HomeController in App Owns Data project is failing

### ISSUE THREAD

**Issue by YasothaDeviSivanandham** [Microsoft/PowerBI-Developer-Samples#29]
File: HomeController.cs 
Method: EmbedReport(string username, string roles)
Issue:
 var authenticationResult = await authenticationContext.AcquireTokenAsync(ResourceUrl, ClientId, credential); 
This method is giving AADSTS70002: The request body must contain the following parameter: 
'client_secret or client_assertion.

Are supposed to use different approach?

**Comment by ali-hamud** [comment]
Please register AAD application as native app and try again.

**Comment by YasothaDeviSivanandham** [comment]
Hi,
   I have registered my app as Native App already
