### ISSUE TITLE
Confused about pricing

### ISSUE THREAD

**Issue by gabrielcraveiro** [Microsoft/PowerBI-Developer-Samples#31]
I know that this is not the place.. , but I'm tasked with using the app owns data to show a filtered report to my company clients and after searching for days I am still struggling with the price model.

If I use the app owns data on my website using a pro account, so my clients can see the reports with filters, will I need embedded or only a powerbi pro account ? This whole powerbi pricing model is confusing to me.

Sorry again and thanks!

**Comment by ali-hamud** [comment]
Hi,
you can use Pro account in development phase but you cannot go live with it due to license.
so, develop using pro account, but Embedded once you want to deploy your solution. just buy capacity and assign it to your workspace.

if you need more information let me know.

**Comment by gabrielcraveiro** [comment]
Hey ali!

So if I go live I will need to pay for the embedded on azure to get capacity. Does embedded need a power bi premium account or just the pro? 

Thanks!

**Comment by ali-hamud** [comment]
yes premium.
