### ISSUE TITLE
authenticationContext.AcquireTokenAsync() method is failing with error

### ISSUE THREAD

**Issue by RaviPwC** [Microsoft/PowerBI-Developer-Samples#32]
Hello team,

I am trying to test the "AppOwnsData" sample after registering a new Native App using a Power BI Pro account and updating the web.config with all required appsettings such as clientid, groupid, reportid, pbiusername and pbipassword.

However, in the HomeController.cs I get an exception in below line:
var authenticationResult = await authenticationContext.AcquireTokenAsync(ResourceUrl, ClientId, credential);

ErrorCode: accessing_ws_metadata_exchange_failed
StatusCode: 404
Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: accessing_ws_metadata_exchange_failed: Accessing WS metadata exchange failed

I have also set the required permissions for the App in Azure portal and granted permissions as well. Not sure why I get this error

**Comment by ali-hamud** [comment]
Please make sure that you requested this permission in app registration:
![image](https://user-images.githubusercontent.com/23071967/34916972-ad51b534-f948-11e7-9dfc-584c696bcbc8.png)

If this doesn't work for you, we will need more details to help you. please file a support ticket and we will help you.
