### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by benjamin-fenker-tessella** [Microsoft/PowerBI-Developer-Samples#34]
I'm finding that the PBIWebApp (Dashboards Sample) under the User Owns Data directory fails to build.

The error message is 

    'Settings' does not contain of definition for 'AADAuthoritySignInUri' and no extension method for 'AADAuthoritySignInUri' accepting a first argument of type 'Settings' could not be found

This ossurs in Default.aspx.cs+72 and redirect.aspx.cs+22. There is also a similar error for `AADAuthoritySignOffUri` in Default.aspx.cs+103.

**Comment by ali-hamud** [comment]
I will take a look.

**Comment by werxes** [comment]
Same issue. Any results?

**Comment by ali-hamud** [comment]
Fixed, please sync.

**Comment by ambalika07** [comment]
I am facing same issue. Can anyone help me out with this one.
