### ISSUE TITLE
PowerBI  register your app It is not normal to open

### ISSUE THREAD

**Issue by yeacer** [Microsoft/PowerBI-Developer-Samples#35]
PowerBI  this website https://dev.powerbi.com/apps, It is not normal to open! I can't make a normal landing,I can't register properly app.
![0 np 4dl6jeq b5d1bc h](https://user-images.githubusercontent.com/35021799/34548017-49c97d78-f13a-11e7-8edb-f9f7f63f62d0.jpg)
![yw_5s 41c u5 y 2yq p](https://user-images.githubusercontent.com/35021799/34548036-6e69c6f6-f13a-11e7-8df8-983d6f0beaf2.png)
I hope to get your help!

**Comment by somriar** [comment]
i can't repro this, is this still happens to you?

**Comment by gilcrespo** [comment]
Yes, it is happening. I just tested on Firefox, Internet Explorer 11 and Opera. 
The main problem is loading this file: “https://dev.powerbi.com/appreg/scripts/powerbiappreg.bundle.js”

**Comment by somriar** [comment]
hey, 
this should be resolved in a few hours, please let us know when/if this is resolved for you.

**Comment by gilcrespo** [comment]
Solved ! thanks my friend :)

**Comment by somriar** [comment]
great! :)
