### ISSUE TITLE
Push data to dataset from Javascript.

### ISSUE THREAD

**Issue by Kalemstorm94** [Microsoft/PowerBI-Developer-Samples#37]
Hello! 

I have a problem using the AppOwnsData solution. I have a dashboard with one report, that uses a streaming dataset. I want to know if it is possible to push data to that dataset from javascript/typescript. 

I've successfully pushed data from C# and Python using PUT or POST methods, but I have no idea how to do this using Javascript. 

Can you please give me some suggestions?

**Comment by ali-hamud** [comment]
I think you should not do it with javascript as you will need Read-Write token in your client. actually it depends in your scenario.

Anyway, if you want to do it, you will need to use Ajax to make a call to your server side API. API handler will use C# SDK or Power BI REST API to push data to streaming dataset.
