### ISSUE TITLE
groupId

### ISSUE THREAD

**Issue by jeffersonmello** [Microsoft/PowerBI-Developer-Samples#38]
What is groupId? how do have?

**Comment by gilcrespo** [comment]
Hello my friend. This one was my first question too.
I strongly recommend you to watch this video: https://www.youtube.com/watch?v=GPHHdDRSlis  where Adam explain very well this topic.

**Comment by jeffersonmello** [comment]
Ok thanks,
Can you add me on skype? I'm with some doubts I saw that you're from Brazil, if you can help me ...

**Comment by ali-hamud** [comment]
group Id is the workspace Id. you can get it from report URL in powerbi.com or by calling Power BI Groups API.
