### ISSUE TITLE
User Owns Data login problem

### ISSUE THREAD

**Issue by yeacer** [Microsoft/PowerBI-Developer-Samples#41]
Use User Owns Data integrated into the web, why must log in once in order to get the report, you can set the single sign-on mode? If the user name and password are set in the configuration file, the Power BI login box will not pop up。Looking forward to your reply, thanks

**Comment by tarostok** [comment]
Our sample for User Owns data doesn't support non interactive sign-in (providing credentials through config file).
AAD doesn't support non-interactive sign-in for AAD Web application.

What you can do, is look on our App owns data sample which gets user credentials from config file and apply it to your User Owns data scenario. 
Please note that you need to register AAD native application for that.

Thanks,
Tal

**Comment by ali-hamud** [comment]
Please reopen if you have more questions.
