### ISSUE TITLE
Client Secret missing in request

### ISSUE THREAD

**Issue by ThomasMldr** [Microsoft/PowerBI-Developer-Samples#46]
When running the EmbedReport sample from the AppOwnsData solution, the request fails with the following message:
The request body must contain the following parameter: 'client_secret or client_assertion'.
and indeed in the code the client secret isn't specified anywhere. [Step 2 of the readme.md](https://github.com/Microsoft/PowerBI-Developer-Samples#step-2---change-webconfig) however states that this should be set in the Web.config. I assume the readme is outdated, but what about the client_secret then?
Thanks in advance!

**Comment by mshmordo** [comment]
Hi,
Can you please verify that you have registered the application as Native application.

Thanks
Mounir

**Comment by ThomasMldr** [comment]
Hi  Mounir, 
I've registered the app, but as a Server-side Web App, not as a Native App.

**Comment by mshmordo** [comment]
that's explain this errors, 
You need to register a new app "Native" as described in the documentation.

-Mounir

**Comment by ThomasMldr** [comment]
Could you point me to this piece of the documentation, please? 
Since the example (and the app that I plan to embed a report in) are in fact Web apps and not native apps, this seems a bit odd and counter-intuitive.
Kind regards

**Comment by mshmordo** [comment]
Its in the documentation (https://github.com/Microsoft/PowerBI-Developer-Samples/blob/master/README.md)  at the top, but I totally agree its not clear!
We will review and improve the documentation.

Regards
Mounir

**Comment by ThomasMldr** [comment]
Hah, okay sorry the next line on [docs.microsoft.com](https://docs.microsoft.com/en-us/power-bi/developer/register-app) also says:

> You will also choose *Native app if you are embedding content for your customers regardless of what the actual application is. Even for web applications.***


MY BAD! Thanks Mounir!
