### ISSUE TITLE
Javascript exception

### ISSUE THREAD

**Issue by eduardohh** [Microsoft/PowerBI-Developer-Samples#5]
Hi,

Debuging the app, I get this javascript exception: 0x800a1391 - JavaScript runtime error: 'Promise' is undefined.

The error occurs in windowPostMessageProxy.js file when I click on **Embed Dashboard** button.

Attach a screenshot.

![image](https://cloud.githubusercontent.com/assets/27864377/25349450/7f29d5d8-28e7-11e7-9b29-dde4cf732639.png)

**Comment by ali-hamud** [comment]
I bit it's in IE.
I will keep this issue open until we add this library to the sample.
All what you need to do is to reference a es6-promis library.
here is an example of such library:
<script src="https://npmcdn.com/es6-promise@3.2.1"></script>

**Comment by ali-hamud** [comment]
please sync. solved.
