### ISSUE TITLE
Sample & recommendation to embed Power BI reports inside UWP App 

### ISSUE THREAD

**Issue by sanjaydebnath** [Microsoft/PowerBI-Developer-Samples#9]
With latest ADAL library (.net core) we can not use 'UserPasswordCredential' ([please refer](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/482)). So how are we supposed to get & build a new PowerBIClient()? Is there any way to get _tokenCredentials_ except using _userid_ and _password_? Seems the recommended way is to use userid & password as described [here](https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-integrate-report-get-report/). But  ADAL is recommending something else. This is to embed report within an UWP App with non-Power BI users.

**Comment by sanjaydebnath** [comment]
Also 'loadreport' is not working, e.g. this is not working 
`<html>
<body>
<iframe id="iFrameEmbedReport"></iframe>
</body>  
<script type="text/javascript">
window.onload = function () {
    var iframe = document.getElementById('iFrameEmbedReport');
        iframe.src = 'https://app.powerbi.com/reportEmbed?reportId=******-088f-4967-***-279bd5a**df&groupId=*****-****-4033-862d-1cd4f4fa72c1';
        iframe.onload = function() 
		{
			var m = {
				action: 'loadReport',
				accessToken: 'H4s*****'
			};
			message = JSON.stringify(m);
			iframe = document.getElementById('iFrameEmbedReport');
			iframe.contentWindow.postMessage(message, "*");
		};
};
</script>
</html>`

**Comment by ali-hamud** [comment]
Hi,
I have no solution yet to this problem.
ADAL library for (.net core) doesn't have UserPasswordCredential.
I don't think I will have a solution soon. but I will pass the issue to my team.

I am closing this issue as it similar to this:
https://github.com/Microsoft/PowerBI-Developer-Samples/issues/3

please follow there.

**Comment by wind-rider** [comment]
A possible way could be using client certificate authentication - I got this answer when asking for an asp.net Core app running against .net core (see https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/482#issuecomment-316973560)

**Comment by argrithmag** [comment]
@sanjaydebnath  did you ever figure out what the difference between your demo and working?  I'm having the same issue with a reactjs app that is unable to display a report.  If I put my tokens, ids, etc in the demo and working examples you posted, working works, demo fails "Unable to display..."
